/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.ComboBoxItem;
import util.Perferencia;
import util.Tabela;

/**
 *
 * @author ayrton.antonio
 */
abstract public class FormPadrao extends javax.swing.JInternalFrame {

    public JLabel jlblConsulta;
    JTextField jtxtConsulta;
    ResourceBundle messages = ResourceBundle.getBundle("messages", new Locale(Perferencia.Idioma));
    JTable tabela;
    DefaultTableModel model = new DefaultTableModel();
    Tabela utilTabela = new Tabela();
    
    
    abstract void inicializacaoComponentesFilho();
    abstract void Guardar();
    abstract void CriarTabela();
    abstract void ConsultarView();
    abstract void ActualizarFormulario();
    abstract void ExcluirView();
    /**
     * Creates new form FormPadtrao
     */
    public FormPadrao() {
        initComponents();
        HilitarBotoes(true);
        HabilitarCamposEditaveis(false);
        inicializacaoComponentesFilho();
        CriarTabela();
        
        jlblConsulta = new JLabel("Consulta");
        jlblConsulta.setBounds(9, 5, 50, 30);        
        jpnConsulta.add(jlblConsulta);
        
        
        jtxtConsulta = new JTextField();
        jtxtConsulta.setBounds(60, 5, 650, 30);        
        jpnConsulta.add(jtxtConsulta);
        
        jtxtConsulta.addKeyListener(
                new KeyAdapter(){
                    public void keyReleased(KeyEvent e){
                        ConsultarView();
                    }
                }
        );
        
        tabela.addMouseListener(
                new MouseAdapter(){
                    public void mouseClicked(MouseEvent e){
                        ActualizarFormulario();
                    }
                }
        );
        
        tabela.addKeyListener(
                new KeyAdapter(){
                    public void keyReleased(KeyEvent e){
                        ActualizarFormulario();
                    }
                }
        );
        
        InternationalizarBotoes();
        Internationalizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnBotoes = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jpnFormulario = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jpnConsulta = new javax.swing.JPanel();

        jpnBotoes.setPreferredSize(new java.awt.Dimension(568, 80));

        jbNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\novo.png")); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\edit.png")); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\remove.png")); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\fechar.png")); // NOI18N
        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\cancel.png")); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayrton.antonio\\Documents\\NetBeansProjects\\AgeContactos\\src\\main\\java\\img\\salvar.png")); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnBotoesLayout = new javax.swing.GroupLayout(jpnBotoes);
        jpnBotoes.setLayout(jpnBotoesLayout);
        jpnBotoesLayout.setHorizontalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbNovo)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir)
                .addGap(46, 46, 46)
                .addComponent(jbGuardar)
                .addGap(18, 18, 18)
                .addComponent(jbCancelar)
                .addGap(36, 36, 36)
                .addComponent(jbFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnBotoesLayout.setVerticalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbGuardar)
                        .addComponent(jbCancelar)
                        .addComponent(jbFechar))
                    .addGroup(jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovo)
                        .addComponent(jbAlterar)
                        .addComponent(jbExcluir)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jpnFormulario.setPreferredSize(new java.awt.Dimension(706, 180));

        jLabelID.setText("ID");

        jLabelDescricao.setText("Descrição");

        javax.swing.GroupLayout jpnFormularioLayout = new javax.swing.GroupLayout(jpnFormulario);
        jpnFormulario.setLayout(jpnFormularioLayout);
        jpnFormularioLayout.setHorizontalGroup(
            jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFormularioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnFormularioLayout.setVerticalGroup(
            jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFormularioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jLabelDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jpnConsulta.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jpnConsultaLayout = new javax.swing.GroupLayout(jpnConsulta);
        jpnConsulta.setLayout(jpnConsultaLayout);
        jpnConsultaLayout.setHorizontalGroup(
            jpnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnConsultaLayout.setVerticalGroup(
            jpnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(jpnFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(jpnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        HilitarBotoes(false);
        HabilitarCamposEditaveis(true);
        LimparCampos();
        txtID.setEnabled(false);
        txtDescricao.requestFocus();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        HilitarBotoes(false);
        HabilitarCamposEditaveis(true);
        txtDescricao.requestFocus();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed

        if(JOptionPane.showConfirmDialog(null,
            "Deseja realmente efetivar a exclusão?", 
            "Excluir Registo", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
        {
            ExcluirView();
            ConsultarView();
            LimparCampos();
        }
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        HilitarBotoes(true);
        HabilitarCamposEditaveis(false);
        Guardar();
        ConsultarView();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        HilitarBotoes(true);
        HabilitarCamposEditaveis(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    public void SelecionarItemComboBoxPorNome(JComboBox comboBox, String nomeDesejado) {
        
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            ComboBoxItem item = (ComboBoxItem)comboBox.getItemAt(i);
            if (item.getDescricao().equals(nomeDesejado)) {
                comboBox.setSelectedIndex(i);
                return; 
            }
        }
    }
    
    public void HilitarBotoes(boolean estado){
        //Botões de Confirmação
        jbGuardar.setEnabled(!estado);        
        jbCancelar.setEnabled(!estado);
        
        //Botões de operação
        jbNovo.setEnabled(estado);        
        jbAlterar.setEnabled(estado);      
        jbExcluir.setEnabled(estado);
    }
    
    public void HabilitarCamposEditaveis(boolean estado){
        txtID.setEnabled(estado);
        txtDescricao.setEnabled(estado);
    }

    public void LimparCampos(){
        txtID.setText("");        
        txtDescricao.setText("");

    }
    public void Internationalizar() {
        
        jLabelID.setText(messages.getString("campo.Id"));
        jLabelDescricao.setText(messages.getString("campo.Description"));
        jlblConsulta.setText(messages.getString("campo.Query"));
    }
    public void InternationalizarBotoes() {
        
        jbNovo.setText(messages.getString("botao.New"));
        jbCancelar.setText(messages.getString("botao.Cancel"));
        jbExcluir.setText(messages.getString("botao.Delete"));
        jbFechar.setText(messages.getString("botao.Close"));
        jbGuardar.setText(messages.getString("botao.Save"));
        jbAlterar.setText(messages.getString("botao.Update"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelDescricao;
    public javax.swing.JLabel jLabelID;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JPanel jpnBotoes;
    public javax.swing.JPanel jpnConsulta;
    public javax.swing.JPanel jpnFormulario;
    public javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
